version: 2.1
jobs:
  deploy:
    docker:
      - image: alpine:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'a5:9b:8e:93:39:92:e9:62:97:e5:b5:10:da:ca:1d:fe'
      - run:
          command: apk --update add git python openssh
          name: Download dependencies
      - run:
          command: git config --global user.name 'Josh Junon' && git config --global user.email 'josh@junon.me'
          name: Configure Git
      - checkout
      - run:
          command: git checkout -b docs && git fetch origin docs && git reset --hard origin/docs
          name: Pull existing docs branch
      - run:
          command: python build.py > index.json
          name: Build documentation index
      - run:
          command: 'git add -A && (git commit -m "$(git log -1 --pretty=%B master) [skip ci]" ||:) && git push origin docs'
          name: Deploy documentation

workflows:
  version: 2
  build_and_deploy_docs:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
